### ISSUE TITLE
Заголовки и СЕО (пункт 11)

### ISSUE THREAD

**Issue by Dr-Nikson** [StartupMakers/react-fullstack#3]
Предлагаю более мощную альтернативу - https://github.com/nfl/react-helmet

Позволяет управлять не только заголовком, но и всей мета-информацией.

**Comment by DenisIzmaylov** [comment]
Да, спасибо! Мы как раз сейчас смотрим на него и выглядит почти как единственно верным решением.

Как я понимаю conditional comments про IE там не поддерживаются?
